---
- name: install nginx
  hosts: first
  become: yes

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present

    - name: Ensure string "Welcome to nginx" is changed
      lineinfile:
        path: /var/www/html/index.nginx-debian.html
        regexp: "^<h1>Welcome to nginx!</h1>"
        line: <script> document.write(new Date().toLocaleDateString()); </script>
---
